import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
// import 'Login_section/welcome_screen.dart';
// import 'Login-section/login_or_register.dart';
// import '../Register-section/otp_verify.dart';
// import '../Register-section/enter_phoneno.dart';
// import '../Register-section/set_tpin.dart';
// import '../Login_section/email_phone_option_screen.dart';


void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Pass the Firebase options from firebase_options.dart
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'TeenPay',
      theme: ThemeData(primarySwatch: Colors.blue),
      
      // home: EmailPhoneLoginScreen(),

    );
  }
}
