import 'package:flutter/material.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'Login-section/welcome_screen.dart';
import 'Login-section/login_or_register.dart'; // import your file
import 'Login-section/otp_verify.dart'; //
import 'Login-section/enter_phoneno.dart'; //
import 'Set_details_section/set_details.dart'; 
import 'Set_details_section/set_mpin.dart'; // import your file

void main() {
  //  WidgetsFlutterBinding.ensureInitialized();
  // await Firebase.initializeApp();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'TeenPay',
      theme: ThemeData(primarySwatch: Colors.blue),
      // home: const WelcomeScreen(),
      // home: const LoginOrRegisterScreen(),
       home:OTPVerificationScreen(),
      //  home:PhoneNumberEntryScreen(),
      // home: SetDetailsScreen(),
      // home: SetNewPinScreen(),

    );
  }
}
