import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
// import '../firebase_options.dart'; // Generated by FlutterFire CLI
// import '../welcome_screen.dart';
import '../Login_section/email_phone_option_screen.dart';
import '../Post-kyc-registration/setusername_pass.dart';



class DashboardScreen extends StatelessWidget {
  const DashboardScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Dashboard')),
      body: const Center(
        child: Text(
          'Welcome to your Dashboard!',
          style: TextStyle(fontSize: 22, fontWeight: FontWeight.bold),
        ),
      ),
    );
  }
}
